// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	LoginPlatform int32                  `protobuf:"varint,3,opt,name=loginPlatform,proto3" json:"loginPlatform,omitempty"`
	SmsCode       string                 `protobuf:"bytes,4,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterParams) Reset() {
	*x = RegisterParams{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterParams) ProtoMessage() {}

func (x *RegisterParams) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterParams.ProtoReflect.Descriptor instead.
func (*RegisterParams) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterParams) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterParams) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterParams) GetLoginPlatform() int32 {
	if x != nil {
		return x.LoginPlatform
	}
	return 0
}

func (x *RegisterParams) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleList      []string               `protobuf:"bytes,2,rep,name=roleList,proto3" json:"roleList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RegisterResponse) GetRoleList() []string {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type SaveInternalCertificationParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInternalCertificationParams) Reset() {
	*x = SaveInternalCertificationParams{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInternalCertificationParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInternalCertificationParams) ProtoMessage() {}

func (x *SaveInternalCertificationParams) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInternalCertificationParams.ProtoReflect.Descriptor instead.
func (*SaveInternalCertificationParams) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *SaveInternalCertificationParams) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (x *SaveInternalCertificationParams) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type SaveInternalCertificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientID      string                 `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveInternalCertificationResponse) Reset() {
	*x = SaveInternalCertificationResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveInternalCertificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveInternalCertificationResponse) ProtoMessage() {}

func (x *SaveInternalCertificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveInternalCertificationResponse.ProtoReflect.Descriptor instead.
func (*SaveInternalCertificationResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *SaveInternalCertificationResponse) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"\x86\x01\n" +
	"\x0eRegisterParams\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12$\n" +
	"\rloginPlatform\x18\x03 \x01(\x05R\rloginPlatform\x12\x18\n" +
	"\asmsCode\x18\x04 \x01(\tR\asmsCode\"@\n" +
	"\x10RegisterResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\broleList\x18\x02 \x03(\tR\broleList\"a\n" +
	"\x1fSaveInternalCertificationParams\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID\x12\"\n" +
	"\fclientSecret\x18\x02 \x01(\tR\fclientSecret\"?\n" +
	"!SaveInternalCertificationResponse\x12\x1a\n" +
	"\bclientID\x18\x01 \x01(\tR\bclientID2=\n" +
	"\vUserService\x12.\n" +
	"\bRegister\x12\x0f.RegisterParams\x1a\x11.RegisterResponse2\x81\x01\n" +
	"\x1cInternalCertificationService\x12a\n" +
	"\x19SaveInternalCertification\x12 .SaveInternalCertificationParams\x1a\".SaveInternalCertificationResponseB\fZ\n" +
	"user/pb;pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*RegisterParams)(nil),                    // 0: RegisterParams
	(*RegisterResponse)(nil),                  // 1: RegisterResponse
	(*SaveInternalCertificationParams)(nil),   // 2: SaveInternalCertificationParams
	(*SaveInternalCertificationResponse)(nil), // 3: SaveInternalCertificationResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: UserService.Register:input_type -> RegisterParams
	2, // 1: InternalCertificationService.SaveInternalCertification:input_type -> SaveInternalCertificationParams
	1, // 2: UserService.Register:output_type -> RegisterResponse
	3, // 3: InternalCertificationService.SaveInternalCertification:output_type -> SaveInternalCertificationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
