metricPort: 5854
appName: user
log:
  level: info # info error warn
  format: console # console 有颜色  json 无颜色
  prefix: "[test/dazhou]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1
grpc:
  addr: 127.0.0.1:11500
etcd:
  addrList:
    - 127.0.0.1:2379
  register:
    name: user
    addr: 127.0.0.1:11500
    version: v1
    weight: 10
    ttl: 10
db:
  mongo:
    url: mongodb://localhost:27017
    userName: root
    password: 123456
    minPoolSize: 10
    maxPoolSize: 100
    db: base
  redis:
    addr: localhost:6379
    poolSize: 10
    minIdleConnList: 1
    password:
jwt:
  secret: 123456
  exp: 7